version: '2.1'

services:
 rancher:
  image: rancher/server:v1.6.6
  restart: always
  labels:
   - "traefik.enable=true"
   - "traefik.backend=rancher"
   - "traefik.frontend.rule=Host:localhost"
   - "traefik.port=8080"
  networks:
   - backend
   - frontend
 traefik:
  image: traefik:1.3.1
  restart: always
  command: --logLevel=DEBUG
  userns_mode: "host"
  privileged: true
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./traefik:/etc/traefik
   - /var/run/docker.sock:/var/run/docker.sock:ro
  networks:
   - backend
   - frontend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
